-- ==========================================
-- PHASE 7: ACTIVITY LOGS & CHAT PERSISTENCE
-- ==========================================

-- 1. ACTIVITY LOGS
create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid default auth.uid(),
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb default '{}',
  created_at timestamptz default now()
);

alter table public.activity_logs enable row level security;

-- Only authenticated admins can view and insert logs
create policy "Admins can view all logs" 
  on public.activity_logs for select
  using ( auth.role() = 'authenticated' );

create policy "Admins can insert logs" 
  on public.activity_logs for insert
  with check ( auth.role() = 'authenticated' );


-- 2. CHAT CONVERSATIONS
create table if not exists public.chat_conversations (
  id uuid default gen_random_uuid() primary key,
  guest_session_id uuid not null,
  last_message_at timestamptz default now(),
  status text default 'active',
  metadata jsonb default '{}',
  created_at timestamptz default now()
);

alter table public.chat_conversations enable row level security;

-- Admin access: Full
create policy "Admins can manage conversations" 
  on public.chat_conversations for all
  using ( auth.role() = 'authenticated' );

-- Public access: Insert only (no read to keep privacy)
create policy "Public can start conversations" 
  on public.chat_conversations for insert
  with check ( true );

-- 3. CHAT MESSAGES
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid references public.chat_conversations(id) on delete cascade,
  role text not null, -- 'user' or 'assistant'
  content text not null,
  created_at timestamptz default now()
);

alter table public.chat_messages enable row level security;

-- Admin access: Full
create policy "Admins can manage messages" 
  on public.chat_messages for all
  using ( auth.role() = 'authenticated' );

-- Public access: Insert only
create policy "Public can send messages" 
  on public.chat_messages for insert
  with check ( true );
